/**
 * cli/lib/install-config.cjs — .rcode/config.yaml generation, validation
 * (against ConfigSchema, #250), and a minimal YAML parser sufficient for
 * that file's scalar-only shape.
 *
 * Split out of cli/install.js (#1066 Phase 1) — mechanical move, no
 * behavior change. Not to be confused with cli/lib/config.cjs, which is
 * the CLI's own unrelated runtime config domain.
 */

const { z } = require('zod');

// Zod schema for .rcode/config.yaml validation (#250).
const ConfigSchema = z.object({
  user_name: z.string().min(1),
  project_name: z.string().min(1),
  communication_language: z.string().default('English'),
  mode: z.enum(['guided', 'yolo'], {
    errorMap: () => ({ message: 'expected "guided" or "yolo"' }),
  }).default('guided'),
  model_profile: z.string().optional(),
  commit_planning: z.boolean().optional(),
  rcode_source_path: z.string().optional(),
  workflow: z.object({
    research_by_default: z.boolean().optional(),
    plan_checker: z.boolean().optional(),
    post_execute_gates: z.boolean().optional(),
    ui_safety_gate: z.boolean().optional(),
    nyquist_validation: z.boolean().optional(),
  }).optional(),
  output: z.object({
    verbose: z.boolean().optional(),
  }).optional(),
  git: z.object({
    branching_strategy: z.string().optional(),
  }).optional(),
  // Declared for validation only — default ('every') lives in the hook (rcode-hooks.cjs prompt-router).
  // Install does NOT write this key; the nudge behavior itself is controlled by
  // whether hooks were enabled at install time (resolveEnableHooks / --no-hooks)
  // or later via /rcode-enable-hooks.
  prompt_nudge: z.enum(['every', 'once-per-intent', 'when-stale', 'off']).optional(),
}).passthrough();

function sanitizeYamlValue(val) {
  return (val || '').replace(/[\n\r]/g, ' ').replace(/"/g, '\\"');
}

function generateConfigYaml(opts) {
  return [
    '# rcode v2 project config',
    '# Generated by install. Safe to edit.',
    `user_name: "${sanitizeYamlValue(opts.userName)}"`,
    `project_name: "${sanitizeYamlValue(opts.projectName)}"`,
    `communication_language: "${sanitizeYamlValue(opts.language)}"`,
    `mode: "${sanitizeYamlValue(opts.mode)}"`,
    `model_profile: "balanced"`,
    `commit_planning: ${opts.commitPlanning !== false}`,
    'workflow:',
    '  research_by_default: false',
    '  plan_checker: true',
    '  post_execute_gates: true',
    '  ui_safety_gate: true',
    'git:',
    '  branching_strategy: "none"',
    '',
  ].join('\n');
}

/**
 * Validate a parsed config.yaml object against ConfigSchema (#250).
 * Returns { valid: true } or { valid: false, errors: string[] }.
 */
function validateConfig(data) {
  const result = ConfigSchema.safeParse(data);
  if (result.success) return { valid: true };
  const errors = result.error.issues.map((issue) => {
    const field = issue.path.join('.');
    return `  ${field || '(root)'}: ${issue.message}`;
  });
  return { valid: false, errors };
}

/**
 * Parse a minimal YAML key:value file into a plain object.
 * Only handles scalar values — sufficient for config.yaml.
 */
function parseSimpleYaml(text) {
  const obj = {};
  let currentParent = null;
  for (const raw of text.split('\n')) {
    const line = raw.replace(/#.*$/, '');
    if (!line.trim()) continue;
    const indent = line.match(/^(\s*)/)[1].length;
    if (indent === 0) {
      const colonAt = line.indexOf(':');
      if (colonAt === -1) continue;
      const key = line.slice(0, colonAt).trim();
      let val = line.slice(colonAt + 1).trim();
      if (val === '') { currentParent = key; obj[key] = {}; continue; }
      currentParent = null;
      if (val.startsWith('"') && val.endsWith('"')) val = val.slice(1, -1);
      if (val.startsWith("'") && val.endsWith("'")) val = val.slice(1, -1);
      if (val === 'true') val = true;
      else if (val === 'false') val = false;
      obj[key] = val;
    } else if (currentParent && indent > 0) {
      const colonAt = line.indexOf(':');
      if (colonAt === -1) continue;
      const key = line.slice(0, colonAt).trim();
      let val = line.slice(colonAt + 1).trim();
      if (val.startsWith('"') && val.endsWith('"')) val = val.slice(1, -1);
      if (val === 'true') val = true;
      else if (val === 'false') val = false;
      obj[currentParent][key] = val;
    }
  }
  return obj;
}

module.exports = {
  ConfigSchema,
  sanitizeYamlValue,
  generateConfigYaml,
  validateConfig,
  parseSimpleYaml,
};
